source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '13.0'

target 'MHSConnector_Example' do
  pod 'MHSConnector', :path => '../'

  target 'MHSConnector_Tests' do
    inherit! :search_paths

    
  end
end
